"""add_user_saved_to_evaluations

Revision ID: 163cc5606836
Revises: 004_financial_unsubscribe
Create Date: 2025-12-23 00:53:19.454814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '163cc5606836'
down_revision = '004_financial_unsubscribe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluations', sa.Column('user_saved', sa.String(length=20), nullable=True))
    op.add_column('evaluations', sa.Column('user_notes', sa.Text(), nullable=True))
    op.create_index(op.f('ix_evaluations_user_saved'), 'evaluations', ['user_saved'], unique=False)
    op.drop_constraint('uq_users_unsubscribe_token', 'users', type_='unique')
    op.drop_index('ix_users_unsubscribe_token', table_name='users')
    op.create_index(op.f('ix_users_unsubscribe_token'), 'users', ['unsubscribe_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_unsubscribe_token'), table_name='users')
    op.create_index('ix_users_unsubscribe_token', 'users', ['unsubscribe_token'], unique=False)
    op.create_unique_constraint('uq_users_unsubscribe_token', 'users', ['unsubscribe_token'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_evaluations_user_saved'), table_name='evaluations')
    op.drop_column('evaluations', 'user_notes')
    op.drop_column('evaluations', 'user_saved')
    # ### end Alembic commands ###
