"""add_awards_table

Revision ID: 2f10671d14f6
Revises: 003
Create Date: 2025-12-22 15:55:09.875264

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2f10671d14f6'
down_revision = '003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('awards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('awarding_agency', sa.String(length=255), nullable=True),
    sa.Column('funding_agency', sa.String(length=255), nullable=True),
    sa.Column('vendor', sa.String(length=255), nullable=True),
    sa.Column('vendor_uei', sa.String(length=50), nullable=True),
    sa.Column('vendor_duns', sa.String(length=50), nullable=True),
    sa.Column('naics', sa.String(length=6), nullable=True),
    sa.Column('psc_code', sa.String(length=10), nullable=True),
    sa.Column('amount', sa.Numeric(), nullable=True),
    sa.Column('base_amount', sa.Numeric(), nullable=True),
    sa.Column('potential_amount', sa.Numeric(), nullable=True),
    sa.Column('award_type', sa.String(length=50), nullable=True),
    sa.Column('award_date', sa.DateTime(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_award_naics', 'awards', ['naics'], unique=False)
    op.create_index('idx_award_vendor', 'awards', ['vendor_uei'], unique=False)
    op.create_index(op.f('ix_awards_awarding_agency'), 'awards', ['awarding_agency'], unique=False)
    op.create_index(op.f('ix_awards_naics'), 'awards', ['naics'], unique=False)
    op.create_index(op.f('ix_awards_source_id'), 'awards', ['source_id'], unique=False)
    op.create_index(op.f('ix_awards_vendor_uei'), 'awards', ['vendor_uei'], unique=False)
    op.drop_table('dismissed_opportunities')
    op.drop_table('saved_opportunities')
    op.alter_column('companies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('companies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_company_opportunity_scores_opportunity', table_name='company_opportunity_scores')
    op.drop_index('idx_discovery_runs_status_completed', table_name='discovery_runs', postgresql_where="((status)::text = 'completed'::text)")
    op.drop_constraint('uq_evaluation_opp_company', 'evaluations', type_='unique')
    op.create_index(op.f('ix_evaluations_company_id'), 'evaluations', ['company_id'], unique=False)
    op.create_index(op.f('ix_evaluations_opportunity_id'), 'evaluations', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_evaluations_recommendation'), 'evaluations', ['recommendation'], unique=False)
    op.add_column('opportunities', sa.Column('source_type', sa.String(length=50), nullable=True))
    op.add_column('opportunities', sa.Column('issuing_agency', sa.String(length=255), nullable=True))
    op.add_column('opportunities', sa.Column('issuing_sub_agency', sa.String(length=255), nullable=True))
    op.add_column('opportunities', sa.Column('issuing_office', sa.String(length=255), nullable=True))
    op.add_column('opportunities', sa.Column('is_forecast', sa.Boolean(), nullable=True))
    op.add_column('opportunities', sa.Column('forecast_fiscal_year', sa.String(length=10), nullable=True))
    op.add_column('opportunities', sa.Column('forecast_quarter', sa.String(length=10), nullable=True))
    op.add_column('opportunities', sa.Column('forecast_estimated_release', sa.DateTime(timezone=True), nullable=True))
    op.add_column('opportunities', sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('opportunities', sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('opportunities', sa.Column('estimated_value_text', sa.String(length=255), nullable=True))
    op.add_column('opportunities', sa.Column('ingestion_run_id', sa.UUID(), nullable=True))
    op.add_column('opportunities', sa.Column('raw_source', sa.String(length=50), nullable=True))
    op.alter_column('opportunities', 'source_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_index('idx_opp_deadline', table_name='opportunities')
    op.drop_index('idx_opp_naics', table_name='opportunities')
    op.drop_index('idx_opp_set_aside', table_name='opportunities')
    op.drop_index('idx_opp_status', table_name='opportunities')
    op.drop_index('idx_opportunities_eval_status', table_name='opportunities')
    op.drop_constraint('uq_source_source_id', 'opportunities', type_='unique')
    op.create_index('idx_opportunity_source', 'opportunities', ['source'], unique=False)
    op.create_index(op.f('ix_opportunities_evaluation_status'), 'opportunities', ['evaluation_status'], unique=False)
    op.create_index(op.f('ix_opportunities_is_forecast'), 'opportunities', ['is_forecast'], unique=False)
    op.create_index(op.f('ix_opportunities_issuing_agency'), 'opportunities', ['issuing_agency'], unique=False)
    op.create_index(op.f('ix_opportunities_source_id'), 'opportunities', ['source_id'], unique=False)
    op.create_unique_constraint('uq_opportunity_source_id', 'opportunities', ['source', 'source_id'])
    op.drop_column('opportunities', 'office')
    op.drop_column('opportunities', 'sub_agency')
    op.drop_column('opportunities', 'agency')
    op.drop_column('opportunities', 'solicitation_number')
    op.drop_column('opportunities', 'evaluated_at')
    op.alter_column('users', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'email_frequency',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'last_login_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'last_login_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'email_frequency',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('users', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.add_column('opportunities', sa.Column('evaluated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('opportunities', sa.Column('solicitation_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('opportunities', sa.Column('agency', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('opportunities', sa.Column('sub_agency', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('opportunities', sa.Column('office', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint('uq_opportunity_source_id', 'opportunities', type_='unique')
    op.drop_index(op.f('ix_opportunities_source_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_issuing_agency'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_is_forecast'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_evaluation_status'), table_name='opportunities')
    op.drop_index('idx_opportunity_source', table_name='opportunities')
    op.create_unique_constraint('uq_source_source_id', 'opportunities', ['source', 'source_id'], postgresql_nulls_not_distinct=False)
    op.create_index('idx_opportunities_eval_status', 'opportunities', ['evaluation_status'], unique=False)
    op.create_index('idx_opp_status', 'opportunities', ['status'], unique=False)
    op.create_index('idx_opp_set_aside', 'opportunities', ['set_aside_type'], unique=False)
    op.create_index('idx_opp_naics', 'opportunities', ['naics_code'], unique=False)
    op.create_index('idx_opp_deadline', 'opportunities', ['response_deadline'], unique=False)
    op.alter_column('opportunities', 'source_id',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('opportunities', 'raw_source')
    op.drop_column('opportunities', 'ingestion_run_id')
    op.drop_column('opportunities', 'estimated_value_text')
    op.drop_column('opportunities', 'last_seen_at')
    op.drop_column('opportunities', 'closed_at')
    op.drop_column('opportunities', 'forecast_estimated_release')
    op.drop_column('opportunities', 'forecast_quarter')
    op.drop_column('opportunities', 'forecast_fiscal_year')
    op.drop_column('opportunities', 'is_forecast')
    op.drop_column('opportunities', 'issuing_office')
    op.drop_column('opportunities', 'issuing_sub_agency')
    op.drop_column('opportunities', 'issuing_agency')
    op.drop_column('opportunities', 'source_type')
    op.drop_index(op.f('ix_evaluations_recommendation'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_opportunity_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_company_id'), table_name='evaluations')
    op.create_unique_constraint('uq_evaluation_opp_company', 'evaluations', ['opportunity_id', 'company_id'], postgresql_nulls_not_distinct=False)
    op.create_index('idx_discovery_runs_status_completed', 'discovery_runs', ['status', sa.text('completed_at DESC')], unique=False, postgresql_where="((status)::text = 'completed'::text)")
    op.create_index('idx_company_opportunity_scores_opportunity', 'company_opportunity_scores', ['opportunity_id'], unique=False)
    op.alter_column('companies', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('companies', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_table('saved_opportunities',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('opportunity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name='saved_opportunities_opportunity_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='saved_opportunities_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='saved_opportunities_pkey'),
    sa.UniqueConstraint('user_id', 'opportunity_id', name='uq_saved_user_opp', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('dismissed_opportunities',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('opportunity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('dismissed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name='dismissed_opportunities_opportunity_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='dismissed_opportunities_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='dismissed_opportunities_pkey'),
    sa.UniqueConstraint('user_id', 'opportunity_id', name='uq_dismissed_user_opp', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_index(op.f('ix_awards_vendor_uei'), table_name='awards')
    op.drop_index(op.f('ix_awards_source_id'), table_name='awards')
    op.drop_index(op.f('ix_awards_naics'), table_name='awards')
    op.drop_index(op.f('ix_awards_awarding_agency'), table_name='awards')
    op.drop_index('idx_award_vendor', table_name='awards')
    op.drop_index('idx_award_naics', table_name='awards')
    op.drop_table('awards')
    # ### end Alembic commands ###
