"""Initial migration - all models

Revision ID: b899d26a5e3e
Revises: 
Create Date: 2025-12-03 07:01:23.813343

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b899d26a5e3e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('legal_structure', sa.String(length=50), nullable=True),
    sa.Column('address_street', sa.String(length=255), nullable=True),
    sa.Column('address_city', sa.String(length=100), nullable=True),
    sa.Column('address_state', sa.String(length=2), nullable=True),
    sa.Column('address_zip', sa.String(length=10), nullable=True),
    sa.Column('uei', sa.String(length=12), nullable=True),
    sa.Column('naics_codes', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('set_asides', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('capabilities', sa.Text(), nullable=True),
    sa.Column('contract_value_min', sa.DECIMAL(), nullable=True),
    sa.Column('contract_value_max', sa.DECIMAL(), nullable=True),
    sa.Column('geographic_preferences', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opportunities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=False),
    sa.Column('solicitation_number', sa.String(length=100), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notice_type', sa.String(length=50), nullable=True),
    sa.Column('agency', sa.String(length=255), nullable=True),
    sa.Column('sub_agency', sa.String(length=255), nullable=True),
    sa.Column('office', sa.String(length=255), nullable=True),
    sa.Column('naics_code', sa.String(length=6), nullable=True),
    sa.Column('psc_code', sa.String(length=10), nullable=True),
    sa.Column('set_aside_type', sa.String(length=50), nullable=True),
    sa.Column('pop_city', sa.String(length=100), nullable=True),
    sa.Column('pop_state', sa.String(length=2), nullable=True),
    sa.Column('pop_zip', sa.String(length=10), nullable=True),
    sa.Column('posted_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('response_deadline', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('estimated_value_low', sa.DECIMAL(), nullable=True),
    sa.Column('estimated_value_high', sa.DECIMAL(), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_id', name='uq_source_source_id')
    )
    op.create_index('idx_opp_deadline', 'opportunities', ['response_deadline'], unique=False)
    op.create_index('idx_opp_naics', 'opportunities', ['naics_code'], unique=False)
    op.create_index('idx_opp_set_aside', 'opportunities', ['set_aside_type'], unique=False)
    op.create_index('idx_opp_status', 'opportunities', ['status'], unique=False)
    op.create_index(op.f('ix_opportunities_naics_code'), 'opportunities', ['naics_code'], unique=False)
    op.create_index(op.f('ix_opportunities_response_deadline'), 'opportunities', ['response_deadline'], unique=False)
    op.create_index(op.f('ix_opportunities_set_aside_type'), 'opportunities', ['set_aside_type'], unique=False)
    op.create_index(op.f('ix_opportunities_status'), 'opportunities', ['status'], unique=False)
    op.create_table('evaluations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('fit_score', sa.Integer(), nullable=True),
    sa.Column('win_probability', sa.Integer(), nullable=True),
    sa.Column('recommendation', sa.String(length=20), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('strengths', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('weaknesses', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('executive_summary', sa.Text(), nullable=True),
    sa.Column('evaluated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('opportunity_id', 'company_id', name='uq_evaluation_opp_company')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('email_frequency', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('dismissed_opportunities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('dismissed_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'opportunity_id', name='uq_dismissed_user_opp')
    )
    op.create_table('saved_opportunities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'opportunity_id', name='uq_saved_user_opp')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_opportunities')
    op.drop_table('dismissed_opportunities')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_opportunities_status'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_set_aside_type'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_response_deadline'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_naics_code'), table_name='opportunities')
    op.drop_index('idx_opp_status', table_name='opportunities')
    op.drop_index('idx_opp_set_aside', table_name='opportunities')
    op.drop_index('idx_opp_naics', table_name='opportunities')
    op.drop_index('idx_opp_deadline', table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_table('companies')
    # ### end Alembic commands ###
